# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b85a6ff265811ab9c40ec55bad67cfe7641db4a9f6f1acee0ce0f5474d427a08fb60ee32115be9f30ced8555b6ba50e8dcabda6c5705a9b947535a0f8f5fbaa9

test:
  secret_key_base: c4019351bee3e4d63f3b7751f92400eee7bfbb5cf61cd75560e6c05039197385f8cc057780221feef37bca595ead776a098208e69919f43135375e35c8f2234c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
